# Generated by Django 3.2.22 on 2023-10-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0002_auto_20231010_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='HR_Interview_Declaration_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(auto_now=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('qualifications', models.CharField(max_length=200)),
                ('year_of_passout', models.PositiveIntegerField()),
                ('resume', models.FileField(upload_to='resumes/')),
            ],
        ),
    ]
