# Generated by Django 3.2.22 on 2023-10-11 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0003_hr_interview_declaration_form'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HR_Interview_Declaration_Form',
            new_name='HR_Interview_Declaration',
        ),
    ]
