# Generated by Django 3.2.22 on 2023-10-14 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0007_auto_20231014_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hr_interview_declaration',
            name='course',
        ),
    ]
