# Generated by Django 3.2.22 on 2023-10-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0008_remove_hr_interview_declaration_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr_registration',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/hr_images/'),
        ),
    ]
