# Generated by Django 3.2.22 on 2023-10-15 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0009_alter_hr_registration_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Language',
        ),
    ]
