# Generated by Django 3.2.22 on 2023-10-16 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0010_rename_course_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview_question',
            old_name='course_name',
            new_name='language',
        ),
        migrations.CreateModel(
            name='Interview_Question_answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100)),
                ('Interview_Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rms.interview_question')),
            ],
        ),
    ]
