# Generated by Django 3.2.22 on 2023-10-16 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0011_auto_20231016_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview_question_answer',
            old_name='Interview_Question',
            new_name='interview_question',
        ),
    ]
