# Generated by Django 3.2.22 on 2023-10-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0012_rename_interview_question_interview_question_answer_interview_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview_question_answer',
            name='answer',
            field=models.TextField(max_length=500),
        ),
    ]
