# Generated by Django 3.2.22 on 2023-10-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0013_alter_interview_question_answer_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketing_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employ_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/hr_images/')),
            ],
        ),
    ]
