# Generated by Django 3.2.22 on 2023-10-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0014_marketing_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketing_Student_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employ_id', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(auto_now=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('qualifications', models.CharField(max_length=200)),
                ('year_of_passout', models.PositiveIntegerField()),
                ('resume', models.FileField(upload_to='resumes/')),
            ],
        ),
    ]
